/** Stable error codes returned by the API (contracts/api.md §Mã lỗi). The web app translates them. */
export const HTTP_STATUS_BY_ERROR_CODE = {
  AUTH_REQUIRED: 401,
  AUTH_INVALID_CREDENTIALS: 401,
  RATE_LIMITED: 429,
  CSRF_INVALID: 403,
  ACTIVE_ORGANIZATION_REQUIRED: 409,
  MEMBERSHIP_INACTIVE: 403,
  FORBIDDEN: 403,
  RESOURCE_NOT_FOUND: 404,
  VALIDATION_FAILED: 400,
  PASSWORD_POLICY_VIOLATION: 400,
  TOKEN_INVALID_OR_EXPIRED: 410,
  INVITATION_EMAIL_MISMATCH: 403,
  INVITATION_NOT_PENDING: 409,
  ALREADY_MEMBER: 409,
  MEMBER_DEACTIVATED_USE_REACTIVATE: 409,
  MEMBERSHIP_NOT_DEACTIVATED: 409,
  LAST_ADMIN_REQUIRED: 409,
  ACCOUNTABLE_REQUIRED: 409,
  ALREADY_PROJECT_MEMBER: 409,
  NOT_PROJECT_MEMBER: 409,
  INTERNAL_ERROR: 500,
} as const;

export type ErrorCode = keyof typeof HTTP_STATUS_BY_ERROR_CODE;

export const ERROR_CODES = Object.keys(HTTP_STATUS_BY_ERROR_CODE) as readonly ErrorCode[];

export function httpStatusOf(code: ErrorCode): number {
  return HTTP_STATUS_BY_ERROR_CODE[code];
}
